# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx2014/Workspace/realProject/realProject.cache/wt [current_project]
set_property parent.project_path D:/Xilinx2014/Workspace/realProject/realProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/BCD_output.v
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/Screen.v
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/Music.v
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/Controller.v
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/Chef.v
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/Input_Coin.v
  D:/Xilinx2014/Workspace/realProject/realProject.srcs/sources_1/new/VendingM.v
}
catch { write_hwdef -file VendingM.hwdef }
synth_design -top VendingM -part xc7z020clg484-1
write_checkpoint -noxdef VendingM.dcp
catch { report_utilization -file VendingM_utilization_synth.rpt -pb VendingM_utilization_synth.pb }
