# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx2014/Workspace/PknuBillboard_Original/PknuBillboard_Original.cache/wt [current_project]
set_property parent.project_path D:/Xilinx2014/Workspace/PknuBillboard_Original/PknuBillboard_Original.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/Xilinx2014/Workspace/PknuBillboard_Original/PknuBillboard_Original.srcs/sources_1/new/PknuBillboard_Original.v
catch { write_hwdef -file PknuBillboard_Original.hwdef }
synth_design -top PknuBillboard_Original -part xc7z020clg484-1
write_checkpoint -noxdef PknuBillboard_Original.dcp
catch { report_utilization -file PknuBillboard_Original_utilization_synth.rpt -pb PknuBillboard_Original_utilization_synth.pb }
