# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.cache/wt [current_project]
set_property parent.project_path D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.srcs/sources_1/new/Mux_4to1_8bits.v
  D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.srcs/sources_1/new/Sub_8bits.v
  D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.srcs/sources_1/new/Mul_8bits.v
  D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.srcs/sources_1/new/Div_8bits.v
  D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.srcs/sources_1/new/Add_8bits.v
  D:/Xilinx2014/Workspace/ALU_8bits_Instance/ALU_8bits_Instance.srcs/sources_1/new/ALU_8bits_Instance.v
}
catch { write_hwdef -file ALU_8bits_Instance.hwdef }
synth_design -top ALU_8bits_Instance -part xc7z020clg484-1
write_checkpoint -noxdef ALU_8bits_Instance.dcp
catch { report_utilization -file ALU_8bits_Instance_utilization_synth.rpt -pb ALU_8bits_Instance_utilization_synth.pb }
